// ══════════════════════════════════════════════════════════════════
// Auth email templates — the ones InsForge sends, not us.
//
// Password reset and signup verification are the emails this project cannot
// build and send itself. The 6-digit code is generated by InsForge and never leaves it:
// that code is the proof the requester owns the inbox, so handing it to
// the application would defeat the point. InsForge therefore renders and
// sends that email, and the only documented way to set a password is
// `resetPassword({ newPassword, otp })` with a token that descends from
// it. There is no admin endpoint that sets a password directly — checked
// against the TypeScript SDK and the REST API's admin section on
// 2026-09-18.
//
// What InsForge does expose is the template. It keeps them in
// `email.templates`, one row per `template_type`, as plain HTML with
// `{{ token }}` where the code goes. That row is in our own Postgres, so
// the design is ours even though the send is not: we write the branded
// HTML there, InsForge substitutes the code and hands the message to
// SpaceMail.
//
// The catch is language. `email.templates` has `UNIQUE (template_type)`
// and no locale column, and the only variables InsForge substitutes are
// `{{ token }}` and `{{ link }}` — nothing that could carry a locale. One
// row, one language. So the row is rewritten to the caller's language
// immediately before each send. Verified on 2026-09-18 that InsForge
// reads the row per send rather than caching it: two consecutive resets
// with the row changed in between arrived with different templates.
//
// See wildgrove-vault/reference/03-features.md, "Avisos".
// ══════════════════════════════════════════════════════════════════

import { prisma } from "@wildgrove/db"
import { loadEmailTemplate } from "./emails/loadTemplate"

export type AuthEmailLocale = "en" | "es"

export type AuthEmailKind = "reset-password" | "verify-email"

/**
 * InsForge picks the row by `template_type`. The `-code` rows are the ones in
 * use because the backend's `resetPasswordMethod` and `verifyEmailMethod` are
 * `code`; the `-link` rows are only read if either setting ever changes.
 */
const TEMPLATE_TYPE: Record<AuthEmailKind, string> = {
    "reset-password": "reset-password-code",
    "verify-email": "email-verification-code",
}

const SUBJECT: Record<AuthEmailKind, Record<AuthEmailLocale, string>> = {
    "reset-password": {
        en: "Reset your password | Wild Grove",
        es: "Restablece tu contraseña | Wild Grove",
    },
    "verify-email": {
        en: "Verify your email | Wild Grove",
        es: "Verifica tu correo | Wild Grove",
    },
}

export function authEmail(kind: AuthEmailKind, locale: AuthEmailLocale): {
    subject: string
    bodyHtml: string
} {
    return {
        subject: SUBJECT[kind][locale],
        // The file still carries `{{ token }}` untouched: loadEmailTemplate
        // only replaces `{{KEY}}` with no spaces, so InsForge's placeholder
        // passes straight through while {{SITE_URL}} is resolved here.
        bodyHtml: loadEmailTemplate(kind, {}, locale),
    }
}

export function resetPasswordEmail(locale: AuthEmailLocale) {
    return authEmail("reset-password", locale)
}

export function verifyEmailEmail(locale: AuthEmailLocale) {
    return authEmail("verify-email", locale)
}

/**
 * Points one of InsForge's templates at `locale`, and answers whether the row
 * had to change.
 *
 * Call this immediately before asking InsForge to send, and let a failure
 * fall through rather than abort the send: an email in the wrong language is
 * a far smaller problem than no email at all.
 *
 * **This races, and the race is deliberate.** Between the write committing
 * and InsForge reading the row there is a window of a few hundred
 * milliseconds; two sends requested in different languages inside that
 * window can cross, and one person gets the other's language. Closing it
 * would mean holding a database connection across the outbound HTTP call,
 * on a pool capped at one connection per isolate, to prevent a cosmetic
 * failure in flows rate-limited to one email per address per minute. The
 * write is skipped when the row already holds the right language, so in
 * the common case — a run of users sharing a locale — there is no window
 * at all.
 */
export async function syncAuthEmailTemplate(
    kind: AuthEmailKind,
    locale: AuthEmailLocale,
): Promise<{ changed: boolean }> {
    const { subject, bodyHtml } = authEmail(kind, locale)
    const templateType = TEMPLATE_TYPE[kind]

    const updated = await prisma.$executeRaw`
        UPDATE email.templates
        SET subject = ${subject}, body_html = ${bodyHtml}, updated_at = now()
        WHERE template_type = ${templateType}
          AND (subject IS DISTINCT FROM ${subject} OR body_html IS DISTINCT FROM ${bodyHtml})
    `

    return { changed: updated > 0 }
}

export function syncResetPasswordTemplate(locale: AuthEmailLocale) {
    return syncAuthEmailTemplate("reset-password", locale)
}

export function syncVerifyEmailTemplate(locale: AuthEmailLocale) {
    return syncAuthEmailTemplate("verify-email", locale)
}
